{{- if and .Values.config .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
{{ .Values.config.data | indent 2 }}
{{- end }}
