{{- if and .Values.deployment .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.registryHost }}/{{ .Values.image.name }}:{{ .Values.image.version }}
          {{- if .Values.config }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}
          {{- end }}
{{- end }}
