{{- if and .Values.service .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- if .Values.service.protocol }}
    - protocol: {{ .Values.service.protocol }}
    {{- else }}
    - protocol: TCP
    {{- end }}
      {{- if .Values.service.port }}
      port: {{ .Values.service.port }}
      {{- else }}
      port: 8080
      {{- end }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      {{- else }}
      targetPort: 8080
      {{- end }}
  {{- if .Values.service.type }}
  type: {{ .Values.service.type }}
  targetPort: {{ .Values.service.type }}
  {{- else }}
  type: ClusterIP
  {{- end }}
{{- end }}
